### ISSUE TITLE
Error trying to compile in linux (arch)

### ISSUE THREAD

**Issue by zer0-days** [ggerganov/kbd-audio#18]
I change the SDL the #include <SDL.h> to  #include <SDL2/SDL.h> and seems compile but i got a problem in the linker

Scanning dependencies of target view-full-gui
[ 35%] Building CXX object CMakeFiles/view-full-gui.dir/view-full-gui.cpp.o
[ 38%] Linking CXX executable view-full-gui
/usr/bin/ld: CMakeFiles/view-full-gui.dir/view-full-gui.cpp.o: en la función `prepareAudioOut(stParameters const&)':
view-full-gui.cpp:(.text+0x2b3): referencia a `SDL_Init' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x2c2): referencia a `SDL_GetNumAudioDevices' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x2ed): referencia a `SDL_GetAudioDeviceName' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x31a): referencia a `SDL_memset' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x361): referencia a `SDL_memset' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x373): referencia a `SDL_OpenAudioDevice' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x3e8): referencia a `SDL_PauseAudioDevice' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x411): referencia a `SDL_GetError' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x424): referencia a `SDL_LogError' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x429): referencia a `SDL_Quit' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x439): referencia a `SDL_GetError' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x44c): referencia a `SDL_LogError' sin definir
/usr/bin/ld: CMakeFiles/view-full-gui.dir/view-full-gui.cpp.o: en la función `renderWaveform(stParameters&, std::vector<int, std::allocator<int> > const&)':
view-full-gui.cpp:(.text+0x150f): referencia a `SDL_PauseAudioDevice' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x1538): referencia a `SDL_ClearQueuedAudio' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x1548): referencia a `SDL_PauseAudioDevice' sin definir
/usr/bin/ld: CMakeFiles/view-full-gui.dir/view-full-gui.cpp.o: en la función `std::_Function_handler<bool (), main::{lambda()#2}>::_M_invoke(std::_Any_data const&)':
view-full-gui.cpp:(.text+0x1ac4): referencia a `SDL_PollEvent' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x1b02): referencia a `SDL_PollEvent' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x1b2d): referencia a `SDL_GetWindowSize' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x21c1): referencia a `SDL_PauseAudioDevice' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x22b2): referencia a `SDL_GL_MakeCurrent' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x2312): referencia a `SDL_GL_SwapWindow' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x2468): referencia a `SDL_GetWindowID' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x24cf): referencia a `SDL_ClearQueuedAudio' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text+0x24df): referencia a `SDL_PauseAudioDevice' sin definir
/usr/bin/ld: CMakeFiles/view-full-gui.dir/view-full-gui.cpp.o: en la función `main':
view-full-gui.cpp:(.text.startup+0x7d): referencia a `SDL_Init' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text.startup+0x1c4): referencia a `SDL_GL_SetAttribute' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text.startup+0x1d3): referencia a `SDL_GL_SetAttribute' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text.startup+0x1e2): referencia a `SDL_GL_SetAttribute' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text.startup+0x1ee): referencia a `SDL_GL_SetAttribute' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text.startup+0x1fd): referencia a `SDL_GL_SetAttribute' sin definir
/usr/bin/ld: CMakeFiles/view-full-gui.dir/view-full-gui.cpp.o:view-full-gui.cpp:(.text.startup+0x20c): más referencias a `SDL_GL_SetAttribute' sin definir a continuación
/usr/bin/ld: CMakeFiles/view-full-gui.dir/view-full-gui.cpp.o: en la función `main':
view-full-gui.cpp:(.text.startup+0x227): referencia a `SDL_GetCurrentDisplayMode' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text.startup+0x250): referencia a `SDL_CreateWindow' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text.startup+0x25d): referencia a `SDL_GL_CreateContext' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text.startup+0x26c): referencia a `SDL_GL_SetSwapInterval' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text.startup+0x51e): referencia a `SDL_GL_DeleteContext' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text.startup+0x528): referencia a `SDL_DestroyWindow' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text.startup+0x52d): referencia a `SDL_Quit' sin definir
/usr/bin/ld: view-full-gui.cpp:(.text.startup+0x56b): referencia a `SDL_GetError' sin definir
/usr/bin/ld: libImGui.a(imgui_impl_sdl.cpp.o): en la función `ImGui_ImplSDL2_Init(SDL_Window*)':
imgui_impl_sdl.cpp:(.text+0x92): referencia a `SDL_CreateSystemCursor' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xa3): referencia a `SDL_CreateSystemCursor' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xb4): referencia a `SDL_CreateSystemCursor' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xc5): referencia a `SDL_CreateSystemCursor' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0xd6): referencia a `SDL_CreateSystemCursor' sin definir
/usr/bin/ld: libImGui.a(imgui_impl_sdl.cpp.o):imgui_impl_sdl.cpp:(.text+0xe7): más referencias a `SDL_CreateSystemCursor' sin definir a continuación
/usr/bin/ld: libImGui.a(imgui_impl_sdl.cpp.o): en la función `ImGui_ImplSDL2_GetClipboardText(void*)':
imgui_impl_sdl.cpp:(.text+0x131): referencia a `SDL_free' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x136): referencia a `SDL_GetClipboardText' sin definir
/usr/bin/ld: libImGui.a(imgui_impl_sdl.cpp.o): en la función `ImGui_ImplSDL2_ProcessEvent(SDL_Event*)':
imgui_impl_sdl.cpp:(.text+0x220): referencia a `SDL_GetModState' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x22e): referencia a `SDL_GetModState' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x23c): referencia a `SDL_GetModState' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x24b): referencia a `SDL_GetModState' sin definir
/usr/bin/ld: libImGui.a(imgui_impl_sdl.cpp.o): en la función `ImGui_ImplSDL2_Shutdown()':
imgui_impl_sdl.cpp:(.text+0x35e): referencia a `SDL_free' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x388): referencia a `SDL_FreeCursor' sin definir
/usr/bin/ld: libImGui.a(imgui_impl_sdl.cpp.o): en la función `ImGui_ImplSDL2_NewFrame(SDL_Window*)':
imgui_impl_sdl.cpp:(.text+0x3f1): referencia a `SDL_GetWindowSize' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x403): referencia a `SDL_GL_GetDrawableSize' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x485): referencia a `SDL_GetPerformanceCounter' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x4e4): referencia a `SDL_GetMouseState' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x546): referencia a `SDL_GetKeyboardFocus' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x560): referencia a `SDL_CaptureMouse' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x5fc): referencia a `SDL_SetCursor' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x606): referencia a `SDL_ShowCursor' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x628): referencia a `SDL_WarpMouseInWindow' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x63b): referencia a `SDL_ShowCursor' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x691): referencia a `SDL_GetPerformanceFrequency' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x6be): referencia a `SDL_GetWindowPosition' sin definir
/usr/bin/ld: imgui_impl_sdl.cpp:(.text+0x6c9): referencia a `SDL_GetGlobalMouseState' sin definir
/usr/bin/ld: libImGui.a(imgui_impl_sdl.cpp.o): en la función `ImGui_ImplSDL2_SetClipboardText(void*, char const*)':
imgui_impl_sdl.cpp:(.text+0x154): referencia a `SDL_SetClipboardText' sin definir
collect2: error: ld devolvió el estado de salida 1
make[2]: *** [CMakeFiles/view-full-gui.dir/build.make:88: view-full-gui] Error 1
make[1]: *** [CMakeFiles/Makefile2:74: CMakeFiles/view-full-gui.dir/all] Error 2

**Comment by ggerganov** [comment]
It fails to link the SDL libs, but hard to tell what is the actual problem. You could try adding `-D USE_FINDSDL2=1` to your cmake command and see if that helps.

**Comment by zer0-days** [comment]
Fixed! Thanks!
