### ISSUE TITLE
Recall rate

### ISSUE THREAD

**Issue by weddy2019** [ggerganov/kbd-audio#19]
Hey man love the work you done with this. I was wondering can it be used with a microphone plugged into the laptop as opposed to the built in microphone in the laptop? what type of microphone did you use and how did you train the software to recall at a successful rate.

**Comment by ggerganov** [comment]
Yes, you can use an external mic. I've used mostly MacBook and iMac built-in mics.

I recently got a 6-mic array kit - will see if it can improve performance, by combining multiple channels.
