### ISSUE TITLE
Failed to initialize OpenGL loader!  

### ISSUE THREAD

**Issue by 1nulled0** [ggerganov/kbd-audio#21]
Hi , Amazing idea.

i'm running A Kali-Linux and setup process was alright.
but , getting " Failed to initialize OpenGL loader!  " while trying to :

Usage: ./view-gui record.kbd

 Found 1 playback devices:
    - Playback device #0: 'ES1371/ES1373 / Creative Labs CT2518 (Audio PCI 64V/128/5200 / Creative CT4810/CT5803/CT5806 [Sound Blaster PCI]) Analog Stereo'
Opened playback device succesfully!
    Frequency:  24000
    Format:     32784
    Channels:   1
    Samples:    1024
[+] Loading recording from 'output.kbd'
Failed to initialize OpenGL loader!     
------
$ glxinfo | grep "OpenGL version"
OpenGL version string: 2.1 Mesa 19.1.2

$  glxinfo | grep rendering
direct **rendering**: Yes

----

Not sure what is that i'm missed .

**Comment by ggerganov** [comment]
Not sure what is the issue. What happens if you do:

`$ LIBGL_ALWAYS_SOFTWARE=1 ./view-gui record.kbd`

**Comment by 1nulled0** [comment]
@ggerganov ... 

Thanks A Lot.

Using LIBGL_ALWAYS_SOFTWARE=1 ..
 it worked .
