### ISSUE TITLE
error al compilar

### ISSUE THREAD

**Issue by Dari0GR** [ggerganov/kbd-audio#46]
Amigo buen dia. Cuando ejecuto "make" comienza a cargar del 1 al 100% pero en el 28% me muestra : 
/Users/dariogr/Desktop/kbd-audio/keytap-gui.cpp:618:28: warning: variable 'curosum' set but not used [-Wunused-but-set-variable]
                    double curosum = 0.0;
                           ^
1 warning generated.
Y en el 60% me muestra:

/Users/dariogr/Desktop/kbd-audio/keytap.cpp:499:28: warning: variable 'curosum' set but not used [-Wunused-but-set-variable]
                    double curosum = 0.0;
                           ^
/Users/dariogr/Desktop/kbd-audio/keytap.cpp:566:99: warning: format specifies type 'long' but the argument has type 'long long' [-Wformat]
                    printf("        Adding waveform %d - cc = %g, offset = %ld\n", iwaveform, cc, offset);
                                                                           ~~~                    ^~~~~~
                                                                           %lld

Podrías ayudarme por favor. Saludos

**Comment by Dari0GR** [comment]
Podria alguien ayudarme por favor? estoy atorado en esta parte

**Comment by ggerganov** [comment]
Please use English in your posts - there is a higher chance someone will help you.

If you are asking about the meaning of the "warnings" during compilation - these are normal. They are not errors. You can safely ignore them.

**Comment by Dari0GR** [comment]
But when I want to use the tools, for example, ./record output.kbd I get the following:

 ./record output.kbd
Usage: ./record output.kbd [-cN]
    -cN - select capture device N
    -CN - number N of capture channels N

Recording 11 frames per key press
Found 1 capture devices:
    - Capture device #0: 'Built-in Microphone'
Attempt to open capture device 0 : 'Built-in Microphone' ...
Opened capture device succesfully!
    DeviceId:   2
    Frequency:  16000
    Format:     33056 (4 bytes)
    Channels:   2
    Samples:    512
    Audio Filter: 1
    Cutoff frequency: 100 Hz
Capturing audio ..
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed
[1]    2276 abort      ./record output.kbd
