### ISSUE TITLE
CMake .. 

### ISSUE THREAD

**Issue by Dari0GR** [ggerganov/kbd-audio#48]
Good day. When I use cmake .. I get the following:

cmake ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Warning at CMakeLists.txt:78 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Could NOT find FFTW (missing: FFTW_LIBRARIES FFTW_INCLUDE_DIRS) 
CMake Warning at CMakeLists.txt:85 (message):
  Unable to find SDL2 library.  It is either not installed or CMake cannot
  find it.  In the latter case, setting the USE_FINDSDL2 variable might help:

     $ cmake -D USE_FINDSDL2 ..

CMake Error at CMakeLists.txt:90 (message):
  Aborting

-- Configuring incomplete, errors occurred!
See also "/Users/hackgr/Desktop/kbd-audio/build/CMakeFiles/CMakeOutput.log".
See also "/Users/hackgr/Desktop/kbd-audio/build/CMakeFiles/CMakeError.log".

I already tried with brew install sdl2 but I get the following:

brew install SDL2

Warning: No available formula with the name "sdl2".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by tamararobin1982** [comment]
Where is the cmake file?

**Comment by ggerganov** [comment]
There is a working CI for both Ubuntu and MacOS - you have to figure out how to install the third-party dependencies on your system.
