### ISSUE TITLE
Incompleted Readme file (Is this just typo?)

### ISSUE THREAD

**Issue by mindgitrwx** [ggerganov/kbd-audio#7]
It is not work correctly.

```
cd kbd-audio
git submodule update --init
mkdir build && cd build
cmake ..
make
```

It must changed like this way on my ubuntu enviroment. 

```
cd kbd-audio
git submodule update --init
mkdir build && cd build
cmake .
make

```

**Comment by ggerganov** [comment]
No, it's not a typo. My guess is you already have the "build" subfolder created and the `mkdir build && cd build` line fails because the folder already exist. You can either delete the folder and rerun the commands as they are, or simply `cd build` and `cmake ..`
