### ISSUE TITLE
ReferenceError: SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by thijstriemstra** [ggerganov/kbd-audio#9]
Seeing this in the live demo using Firefox 63 on osx 10.14.1:

```
ReferenceError: SharedArrayBuffer is not defined
```

Perhaps you can do a check and show a 'firefox not supported' message (if that's the issue..)

**Comment by thijstriemstra** [comment]
Thanks for the details. Just read [this](http://kripken.github.io/emscripten-site/docs/porting/pthreads.html):

```
As of January 2018, browsers have disabled SharedArrayBuffer due to the Spectre set of vulnerabilities. Until it is restored you can still experiment with it if you flip a pref in your browser.
```

Also see https://caniuse.com/#feat=sharedarraybuffer

Here's an example showing how to catch a ReferenceError: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError#Catching_a_ReferenceError

So something like 

```javascript
try {
  var a = SharedArrayBuffer;
} catch (e) {
  console.log(e instanceof ReferenceError); // true
}
```

**Comment by ggerganov** [comment]
Thanks for the info. I just pushed a small change that should handle the SharedArrayBuffer error slightly better and inform the user how to proceed. It's in my blog repo:

https://github.com/ggerganov/ggerganov.github.io/commit/4c9da7babacda1451eafad5219ff5beed04678e1

**Comment by thijstriemstra** [comment]
Looks good, closing.
